### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by JustKato** [JustKato/drive-health#1]
I am really unhappy with the docker size image being 1.2Gb for such a small program

**Comment by manjarisri** [comment]
hey! I would like to help with this issue

**Comment by JustKato** [comment]
> hey! I would like to help with this issue

Thanks for offering, feel free to create a pull request with any changes you might wanna commit :)

**Comment by manjarisri** [comment]
Hey! i've raised PR, please look into the Dockerfile if it is good to go
